export type ToolStatus = "RUNNING" | "IDLE" | "ERROR" | "SYNCING";

export interface ToolParam {
  name: string;
  type: "text" | "number" | "select" | "boolean";
  label: string;
  placeholder?: string;
  options?: string[];
  defaultValue?: string;
}

export interface Tool {
  id: string;
  name: string;
  moduleId: string;
  status: ToolStatus;
  description: string;
  category: string;
  params: ToolParam[];
}

// ============================================================
// ALL 190+ TOOLS
// ============================================================
export const ALL_TOOLS: Tool[] = [
  // ── CONTROL CENTER (8 tools) ──
  { id: "system.metrics", name: "System Metrics", moduleId: "control-center", status: "RUNNING", category: "monitoring", description: "Real-time CPU, memory, disk, network metrics with historical graphs", params: [{ name: "interval", type: "select", label: "Refresh Interval", options: ["1s", "5s", "10s", "30s"], defaultValue: "5s" }] },
  { id: "system.health", name: "Health Monitor", moduleId: "control-center", status: "RUNNING", category: "monitoring", description: "Service health checks, uptime monitoring, SLA tracking", params: [{ name: "target", type: "text", label: "Target Service", placeholder: "all" }] },
  { id: "system.logs", name: "Log Aggregator", moduleId: "control-center", status: "RUNNING", category: "monitoring", description: "Centralized log collection, filtering, and analysis", params: [{ name: "level", type: "select", label: "Log Level", options: ["ALL", "ERROR", "WARN", "INFO", "DEBUG"], defaultValue: "ALL" }] },
  { id: "system.alerts", name: "Alert Manager", moduleId: "control-center", status: "RUNNING", category: "monitoring", description: "Threshold-based alerting, notification routing, escalation policies", params: [{ name: "severity", type: "select", label: "Min Severity", options: ["LOW", "MEDIUM", "HIGH", "CRITICAL"], defaultValue: "MEDIUM" }] },
  { id: "system.network", name: "Network Monitor", moduleId: "control-center", status: "RUNNING", category: "monitoring", description: "Bandwidth usage, connection tracking, latency monitoring", params: [{ name: "interface", type: "text", label: "Interface", placeholder: "eth0" }] },
  { id: "system.process", name: "Process Manager", moduleId: "control-center", status: "RUNNING", category: "monitoring", description: "Process listing, resource usage, kill/restart capabilities", params: [{ name: "filter", type: "text", label: "Filter", placeholder: "process name" }] },
  { id: "system.disk", name: "Disk Analyzer", moduleId: "control-center", status: "RUNNING", category: "monitoring", description: "Disk usage analysis, I/O monitoring, partition management", params: [{ name: "path", type: "text", label: "Path", placeholder: "/" }] },
  { id: "system.firewall", name: "Firewall Status", moduleId: "control-center", status: "RUNNING", category: "monitoring", description: "Firewall rules, blocked connections, traffic analysis", params: [{ name: "action", type: "select", label: "Action", options: ["status", "list-rules", "block-ip", "unblock-ip"], defaultValue: "status" }] },

  // ── QUANTUM INTEL (8 tools) ──
  { id: "intel.quantum_scan", name: "Quantum Scanner", moduleId: "quantum-intel", status: "RUNNING", category: "intel", description: "Quantum-encrypted network scanning with entanglement-based detection evasion", params: [{ name: "target", type: "text", label: "Target", placeholder: "IP/CIDR" }, { name: "depth", type: "select", label: "Scan Depth", options: ["shallow", "medium", "deep", "quantum"], defaultValue: "medium" }] },
  { id: "intel.key_distribution", name: "QKD Engine", moduleId: "quantum-intel", status: "RUNNING", category: "crypto", description: "Quantum Key Distribution using BB84 protocol simulation", params: [{ name: "bits", type: "number", label: "Key Bits", placeholder: "256" }] },
  { id: "intel.signal_intercept", name: "Signal Interceptor", moduleId: "quantum-intel", status: "RUNNING", category: "intel", description: "RF signal interception, SIGINT analysis, frequency hopping detection", params: [{ name: "frequency", type: "text", label: "Frequency Range", placeholder: "2.4GHz-5GHz" }] },
  { id: "intel.decrypt", name: "Quantum Decryptor", moduleId: "quantum-intel", status: "RUNNING", category: "crypto", description: "Shor's algorithm-based decryption simulation for RSA/ECC", params: [{ name: "algorithm", type: "select", label: "Algorithm", options: ["RSA", "ECC", "AES", "DES", "3DES"], defaultValue: "RSA" }] },
  { id: "intel.entangle", name: "Entanglement Engine", moduleId: "quantum-intel", status: "RUNNING", category: "quantum", description: "Quantum entanglement pair generation and Bell state measurement", params: [{ name: "pairs", type: "number", label: "Qubit Pairs", placeholder: "4" }] },
  { id: "intel.teleport", name: "Quantum Teleporter", moduleId: "quantum-intel", status: "RUNNING", category: "quantum", description: "Quantum state teleportation between nodes using entangled pairs", params: [{ name: "node", type: "text", label: "Target Node", placeholder: "node-id" }] },
  { id: "intel.noise_analysis", name: "Noise Analyzer", moduleId: "quantum-intel", status: "RUNNING", category: "quantum", description: "Quantum channel noise analysis, error rate estimation, decoherence tracking", params: [{ name: "channel", type: "text", label: "Channel", placeholder: "ch-01" }] },
  { id: "intel.grover", name: "Grover Search", moduleId: "quantum-intel", status: "RUNNING", category: "quantum", description: "Grover's quantum search algorithm for unstructured database search", params: [{ name: "database_size", type: "number", label: "Database Size", placeholder: "1000000" }] },

  // ── OSINT DASHBOARD (10 tools) ──
  { id: "osint.social_recon", name: "Social Recon", moduleId: "osint-dashboard", status: "RUNNING", category: "osint", description: "Social media profile discovery, cross-platform correlation, activity timeline", params: [{ name: "username", type: "text", label: "Username", placeholder: "@target" }] },
  { id: "osint.domain_lookup", name: "Domain Intel", moduleId: "osint-dashboard", status: "RUNNING", category: "osint", description: "Domain registration, hosting, DNS records, subdomains, certificates", params: [{ name: "domain", type: "text", label: "Domain", placeholder: "example.com" }] },
  { id: "osint.breach_search", name: "Breach Search", moduleId: "osint-dashboard", status: "RUNNING", category: "osint", description: "Search leaked databases, credential dumps, paste sites", params: [{ name: "email", type: "text", label: "Email/Username", placeholder: "target@email.com" }] },
  { id: "osint.shodan", name: "Shodan Scanner", moduleId: "osint-dashboard", status: "RUNNING", category: "osint", description: "Internet-connected device search, banner grabbing, vulnerability detection", params: [{ name: "query", type: "text", label: "Shodan Query", placeholder: "apache port:443" }] },
  { id: "osint.censys", name: "Censys Search", moduleId: "osint-dashboard", status: "RUNNING", category: "osint", description: "Certificate transparency, host enumeration, protocol analysis", params: [{ name: "query", type: "text", label: "Censys Query", placeholder: "parsed.subject_dn" }] },
  { id: "osint.whois", name: "WHOIS Lookup", moduleId: "osint-dashboard", status: "RUNNING", category: "osint", description: "Domain registrant info, IP allocation, ASN lookup", params: [{ name: "target", type: "text", label: "Domain/IP", placeholder: "example.com" }] },
  { id: "osint.dns_enum", name: "DNS Enumerator", moduleId: "osint-dashboard", status: "RUNNING", category: "osint", description: "DNS zone transfer, subdomain brute-force, record enumeration", params: [{ name: "domain", type: "text", label: "Domain", placeholder: "example.com" }, { name: "wordlist", type: "select", label: "Wordlist", options: ["small", "medium", "large", "custom"], defaultValue: "medium" }] },
  { id: "osint.email_hunter", name: "Email Hunter", moduleId: "osint-dashboard", status: "RUNNING", category: "osint", description: "Email address discovery, verification, pattern detection", params: [{ name: "domain", type: "text", label: "Company Domain", placeholder: "company.com" }] },
  { id: "osint.geolocation", name: "GeoLocator", moduleId: "osint-dashboard", status: "RUNNING", category: "osint", description: "IP geolocation, WiFi triangulation, cell tower mapping", params: [{ name: "ip", type: "text", label: "IP Address", placeholder: "8.8.8.8" }] },
  { id: "osint.dark_web", name: "Dark Web Monitor", moduleId: "osint-dashboard", status: "RUNNING", category: "osint", description: "Dark web marketplace monitoring, paste site scraping, threat intel feeds", params: [{ name: "keyword", type: "text", label: "Keyword", placeholder: "search term" }] },

  // ── DEEP EXTRACTOR (8 tools) ──
  { id: "deep.scrape", name: "Deep Scraper", moduleId: "deep-extractor", status: "RUNNING", category: "extraction", description: "Multi-layer web scraping with JS rendering, CAPTCHA bypass, rate limiting", params: [{ name: "url", type: "text", label: "Target URL", placeholder: "https://..." }, { name: "depth", type: "number", label: "Crawl Depth", placeholder: "3" }] },
  { id: "deep.crawl_onion", name: "Onion Crawler", moduleId: "deep-extractor", status: "RUNNING", category: "extraction", description: ".onion hidden service discovery and content indexing via Tor", params: [{ name: "seed", type: "text", label: "Seed URL", placeholder: ".onion address" }] },
  { id: "deep.extract_data", name: "Data Extractor", moduleId: "deep-extractor", status: "RUNNING", category: "extraction", description: "Structured data extraction from HTML, JSON, XML, PDF, images", params: [{ name: "format", type: "select", label: "Output Format", options: ["JSON", "CSV", "XML", "SQL"], defaultValue: "JSON" }] },
  { id: "deep.discover_services", name: "Service Discovery", moduleId: "deep-extractor", status: "RUNNING", category: "extraction", description: "Hidden service enumeration, API endpoint discovery, sitemap generation", params: [{ name: "target", type: "text", label: "Target", placeholder: "domain or IP" }] },
  { id: "deep.tor_relay", name: "Tor Relay Manager", moduleId: "deep-extractor", status: "RUNNING", category: "network", description: "Tor circuit management, relay selection, exit node control", params: [{ name: "action", type: "select", label: "Action", options: ["new-circuit", "list-relays", "set-exit", "status"], defaultValue: "status" }] },
  { id: "deep.paste_monitor", name: "Paste Monitor", moduleId: "deep-extractor", status: "RUNNING", category: "monitoring", description: "Pastebin/paste site monitoring for leaked credentials and sensitive data", params: [{ name: "keyword", type: "text", label: "Keywords", placeholder: "comma-separated" }] },
  { id: "deep.archive_search", name: "Archive Search", moduleId: "deep-extractor", status: "RUNNING", category: "extraction", description: "Wayback Machine, cached pages, deleted content recovery", params: [{ name: "url", type: "text", label: "URL", placeholder: "https://..." }] },
  { id: "deep.metadata_strip", name: "Metadata Stripper", moduleId: "deep-extractor", status: "RUNNING", category: "utility", description: "Remove EXIF, metadata from files before exfiltration", params: [{ name: "file_type", type: "select", label: "File Type", options: ["image", "pdf", "doc", "all"], defaultValue: "all" }] },

  // ── PAYLOAD VAULT (8 tools) ──
  { id: "payload.generate", name: "Payload Generator", moduleId: "payload-vault", status: "RUNNING", category: "offensive", description: "Generate reverse shells, bind shells, meterpreter, web shells", params: [{ name: "type", type: "select", label: "Payload Type", options: ["reverse_shell", "bind_shell", "meterpreter", "web_shell", "dropper"], defaultValue: "reverse_shell" }, { name: "platform", type: "select", label: "Platform", options: ["windows", "linux", "macos", "android", "ios"], defaultValue: "linux" }] },
  { id: "payload.encode", name: "Encoder", moduleId: "payload-vault", status: "RUNNING", category: "evasion", description: "Multi-stage encoding: XOR, Base64, AES, custom encoders", params: [{ name: "encoder", type: "select", label: "Encoder", options: ["xor", "base64", "aes", "shikata_ga_nai", "custom"], defaultValue: "xor" }] },
  { id: "payload.obfuscate", name: "Obfuscator", moduleId: "payload-vault", status: "RUNNING", category: "evasion", description: "Code obfuscation, string encryption, control flow flattening", params: [{ name: "level", type: "select", label: "Obfuscation Level", options: ["low", "medium", "high", "paranoid"], defaultValue: "medium" }] },
  { id: "payload.deliver", name: "Delivery System", moduleId: "payload-vault", status: "RUNNING", category: "offensive", description: "Payload delivery via email, USB, watering hole, supply chain", params: [{ name: "method", type: "select", label: "Delivery Method", options: ["email", "usb", "watering_hole", "supply_chain", "direct"], defaultValue: "direct" }] },
  { id: "payload.polymorph", name: "Polymorphic Engine", moduleId: "payload-vault", status: "RUNNING", category: "evasion", description: "Self-mutating code generation, signature evasion, metamorphic engine", params: [{ name: "mutations", type: "number", label: "Mutation Cycles", placeholder: "10" }] },
  { id: "payload.crypter", name: "Crypter", moduleId: "payload-vault", status: "RUNNING", category: "evasion", description: "Runtime crypter, FUD generation, AV bypass", params: [{ name: "av_target", type: "select", label: "Target AV", options: ["windows_defender", "kaspersky", "norton", "all"], defaultValue: "all" }] },
  { id: "payload.dropper", name: "Dropper Builder", moduleId: "payload-vault", status: "RUNNING", category: "offensive", description: "Stage 1 dropper creation with anti-sandbox and anti-debug", params: [{ name: "format", type: "select", label: "Format", options: ["exe", "dll", "ps1", "vbs", "hta"], defaultValue: "exe" }] },
  { id: "payload.c2_beacon", name: "C2 Beacon", moduleId: "payload-vault", status: "RUNNING", category: "offensive", description: "Command & Control beacon with jitter, sleep, and fallback channels", params: [{ name: "protocol", type: "select", label: "Protocol", options: ["HTTPS", "DNS", "ICMP", "WebSocket"], defaultValue: "HTTPS" }] },

  // ── ATTACK CONSOLE (8 tools) ──
  { id: "attack.exploit", name: "Exploit Runner", moduleId: "attack-console", status: "RUNNING", category: "offensive", description: "Execute exploits from database, custom exploit loading, chain exploits", params: [{ name: "exploit_id", type: "text", label: "Exploit ID", placeholder: "CVE-2024-XXXX" }, { name: "target", type: "text", label: "Target", placeholder: "IP:PORT" }] },
  { id: "attack.lateral_move", name: "Lateral Movement", moduleId: "attack-console", status: "RUNNING", category: "offensive", description: "Pass-the-hash, token impersonation, RDP hijacking, WMI execution", params: [{ name: "technique", type: "select", label: "Technique", options: ["pth", "token_impersonation", "rdp_hijack", "wmi", "psexec"], defaultValue: "pth" }] },
  { id: "attack.persist", name: "Persistence Engine", moduleId: "attack-console", status: "RUNNING", category: "offensive", description: "Registry keys, scheduled tasks, DLL hijacking, bootkit", params: [{ name: "method", type: "select", label: "Method", options: ["registry", "scheduled_task", "dll_hijack", "service", "bootkit"], defaultValue: "registry" }] },
  { id: "attack.escalate", name: "Privilege Escalation", moduleId: "attack-console", status: "RUNNING", category: "offensive", description: "Kernel exploits, misconfig abuse, token manipulation, UAC bypass", params: [{ name: "os", type: "select", label: "Target OS", options: ["windows", "linux", "macos"], defaultValue: "linux" }] },
  { id: "attack.exfiltrate", name: "Data Exfiltrator", moduleId: "attack-console", status: "RUNNING", category: "offensive", description: "DNS tunneling, steganography, encrypted channels, cloud exfil", params: [{ name: "channel", type: "select", label: "Exfil Channel", options: ["dns", "https", "icmp", "stego", "cloud"], defaultValue: "https" }] },
  { id: "attack.pivot", name: "Pivot Manager", moduleId: "attack-console", status: "RUNNING", category: "offensive", description: "SSH tunneling, SOCKS proxy, port forwarding, VPN pivoting", params: [{ name: "type", type: "select", label: "Pivot Type", options: ["ssh_tunnel", "socks", "port_forward", "vpn"], defaultValue: "socks" }] },
  { id: "attack.credential_dump", name: "Credential Dumper", moduleId: "attack-console", status: "RUNNING", category: "offensive", description: "Mimikatz, SAM dump, LSA secrets, Kerberos tickets, cached creds", params: [{ name: "method", type: "select", label: "Method", options: ["mimikatz", "sam", "lsa", "kerberos", "cached"], defaultValue: "mimikatz" }] },
  { id: "attack.cleanup", name: "Track Cleaner", moduleId: "attack-console", status: "RUNNING", category: "utility", description: "Log wiping, timestamp manipulation, artifact removal", params: [{ name: "scope", type: "select", label: "Scope", options: ["logs", "timestamps", "artifacts", "all"], defaultValue: "all" }] },

  // ── ZXCDDOS (7 tools) ──
  { id: "ddos.stress_test", name: "Stress Tester", moduleId: "zxcddos", status: "RUNNING", category: "testing", description: "HTTP/TCP/UDP stress testing with configurable concurrency", params: [{ name: "target", type: "text", label: "Target", placeholder: "IP:PORT" }, { name: "threads", type: "number", label: "Threads", placeholder: "100" }] },
  { id: "ddos.amplify", name: "Amplification", moduleId: "zxcddos", status: "RUNNING", category: "testing", description: "DNS/NTP/SSDP/Memcached amplification vector testing", params: [{ name: "vector", type: "select", label: "Vector", options: ["DNS", "NTP", "SSDP", "Memcached", "CLDAP"], defaultValue: "DNS" }] },
  { id: "ddos.layer7", name: "Layer 7 Attack", moduleId: "zxcddos", status: "RUNNING", category: "testing", description: "HTTP flood, Slowloris, RUDY, cache bypass attacks", params: [{ name: "method", type: "select", label: "Method", options: ["http_flood", "slowloris", "rudy", "cache_bypass"], defaultValue: "http_flood" }] },
  { id: "ddos.slowloris", name: "Slowloris", moduleId: "zxcddos", status: "RUNNING", category: "testing", description: "Slow HTTP attack keeping connections open with partial headers", params: [{ name: "connections", type: "number", label: "Connections", placeholder: "500" }] },
  { id: "ddos.syn_flood", name: "SYN Flood", moduleId: "zxcddos", status: "RUNNING", category: "testing", description: "TCP SYN flood with spoofed source addresses", params: [{ name: "target", type: "text", label: "Target", placeholder: "IP:PORT" }] },
  { id: "ddos.botnet_sim", name: "Botnet Simulator", moduleId: "zxcddos", status: "RUNNING", category: "testing", description: "Distributed attack simulation from multiple virtual nodes", params: [{ name: "nodes", type: "number", label: "Virtual Nodes", placeholder: "1000" }] },
  { id: "ddos.mitigation_test", name: "Mitigation Tester", moduleId: "zxcddos", status: "RUNNING", category: "defense", description: "Test DDoS mitigation effectiveness, WAF bypass, rate limit testing", params: [{ name: "target", type: "text", label: "Target", placeholder: "URL" }] },

  // ── QUANTUM IDE (7 tools) ──
  { id: "code.edit", name: "Code Editor", moduleId: "quantum-ide", status: "RUNNING", category: "dev", description: "Multi-language editor with syntax highlighting, autocomplete, linting", params: [{ name: "language", type: "select", label: "Language", options: ["python", "javascript", "rust", "go", "c", "java"], defaultValue: "python" }] },
  { id: "code.compile", name: "Compiler", moduleId: "quantum-ide", status: "RUNNING", category: "dev", description: "Multi-language compilation with optimization flags", params: [{ name: "optimization", type: "select", label: "Optimization", options: ["O0", "O1", "O2", "O3", "Os"], defaultValue: "O2" }] },
  { id: "code.debug", name: "Debugger", moduleId: "quantum-ide", status: "RUNNING", category: "dev", description: "Step-through debugging, breakpoints, variable inspection, call stack", params: [{ name: "mode", type: "select", label: "Mode", options: ["step", "continue", "breakpoint", "watch"], defaultValue: "step" }] },
  { id: "code.format", name: "Formatter", moduleId: "quantum-ide", status: "RUNNING", category: "dev", description: "Auto-format code with language-specific style guides", params: [{ name: "style", type: "select", label: "Style", options: ["default", "google", "airbnb", "pep8"], defaultValue: "default" }] },
  { id: "code.analyze", name: "Static Analyzer", moduleId: "quantum-ide", status: "RUNNING", category: "dev", description: "Code quality analysis, complexity metrics, security scanning", params: [{ name: "depth", type: "select", label: "Analysis Depth", options: ["quick", "standard", "deep"], defaultValue: "standard" }] },
  { id: "code.ai_assist", name: "AI Code Assistant", moduleId: "quantum-ide", status: "RUNNING", category: "ai", description: "AI-powered code completion, refactoring, bug detection", params: [{ name: "task", type: "select", label: "Task", options: ["complete", "refactor", "fix_bug", "explain", "optimize"], defaultValue: "complete" }] },
  { id: "code.git", name: "Git Manager", moduleId: "quantum-ide", status: "RUNNING", category: "dev", description: "Git operations, branch management, merge conflict resolution", params: [{ name: "action", type: "select", label: "Action", options: ["status", "commit", "push", "pull", "branch", "merge"], defaultValue: "status" }] },

  // ── ZOMBIE SWARM (7 tools) ──
  { id: "swarm.deploy", name: "Swarm Deployer", moduleId: "zombie-swarm", status: "RUNNING", category: "c2", description: "Deploy zombie nodes to target network with P2P mesh", params: [{ name: "count", type: "number", label: "Node Count", placeholder: "100" }] },
  { id: "swarm.command", name: "Swarm Commander", moduleId: "zombie-swarm", status: "RUNNING", category: "c2", description: "Issue commands to swarm nodes, task distribution, load balancing", params: [{ name: "command", type: "text", label: "Command", placeholder: "exec command" }] },
  { id: "swarm.status", name: "Swarm Status", moduleId: "zombie-swarm", status: "RUNNING", category: "c2", description: "Node health, connectivity map, bandwidth usage, latency", params: [{ name: "view", type: "select", label: "View", options: ["summary", "detailed", "map", "graph"], defaultValue: "summary" }] },
  { id: "swarm.recall", name: "Swarm Recall", moduleId: "zombie-swarm", status: "RUNNING", category: "c2", description: "Recall nodes, self-destruct, evidence cleanup", params: [{ name: "action", type: "select", label: "Action", options: ["recall", "self_destruct", "cleanup"], defaultValue: "recall" }] },
  { id: "swarm.mesh", name: "Mesh Network", moduleId: "zombie-swarm", status: "RUNNING", category: "network", description: "P2P mesh topology management, resilient routing, node discovery", params: [{ name: "topology", type: "select", label: "Topology", options: ["mesh", "star", "ring", "hybrid"], defaultValue: "mesh" }] },
  { id: "swarm.proxy_chain", name: "Proxy Chain", moduleId: "zombie-swarm", status: "RUNNING", category: "network", description: "Multi-hop proxy routing through swarm nodes", params: [{ name: "hops", type: "number", label: "Hop Count", placeholder: "5" }] },
  { id: "swarm.ddos_coord", name: "DDoS Coordinator", moduleId: "zombie-swarm", status: "RUNNING", category: "offensive", description: "Coordinate distributed attacks across swarm nodes", params: [{ name: "target", type: "text", label: "Target", placeholder: "IP:PORT" }] },

  // ── KIMIKUKIU REPOS (7 tools) ──
  { id: "repo.browse", name: "Repo Browser", moduleId: "kimikukiu-repos", status: "RUNNING", category: "dev", description: "Browse GitHub/GitLab repositories, view files, commits, branches", params: [{ name: "url", type: "text", label: "Repo URL", placeholder: "github.com/user/repo" }] },
  { id: "repo.analyze", name: "Code Analyzer", moduleId: "kimikukiu-repos", status: "RUNNING", category: "dev", description: "Code complexity, dependency graph, architecture analysis", params: [{ name: "repo", type: "text", label: "Repository", placeholder: "user/repo" }] },
  { id: "repo.scan_vulns", name: "Vuln Scanner", moduleId: "kimikukiu-repos", status: "RUNNING", category: "security", description: "Scan code for vulnerabilities, secrets, hardcoded credentials", params: [{ name: "scan_type", type: "select", label: "Scan Type", options: ["secrets", "vulns", "deps", "all"], defaultValue: "all" }] },
  { id: "repo.audit_deps", name: "Dependency Auditor", moduleId: "kimikukiu-repos", status: "RUNNING", category: "security", description: "Audit npm/pip/cargo dependencies for known CVEs", params: [{ name: "ecosystem", type: "select", label: "Ecosystem", options: ["npm", "pip", "cargo", "maven", "all"], defaultValue: "all" }] },
  { id: "repo.clone", name: "Repo Cloner", moduleId: "kimikukiu-repos", status: "RUNNING", category: "dev", description: "Clone repositories with depth control and sparse checkout", params: [{ name: "url", type: "text", label: "Clone URL", placeholder: "https://github.com/..." }] },
  { id: "repo.secret_scan", name: "Secret Scanner", moduleId: "kimikukiu-repos", status: "RUNNING", category: "security", description: "Scan git history for leaked API keys, tokens, passwords", params: [{ name: "depth", type: "select", label: "History Depth", options: ["last_commit", "last_100", "full_history"], defaultValue: "last_100" }] },
  { id: "repo.license_check", name: "License Checker", moduleId: "kimikukiu-repos", status: "RUNNING", category: "compliance", description: "Check license compatibility, compliance, SBOM generation", params: [{ name: "format", type: "select", label: "Output", options: ["summary", "spdx", "cyclonedx"], defaultValue: "summary" }] },

  // ── WHOAMISEC GPT (7 tools) ──
  { id: "ai.chat", name: "AI Chat", moduleId: "whoamisec-gpt", status: "RUNNING", category: "ai", description: "Quantum Intelligence Ultra conversational interface", params: [{ name: "mode", type: "select", label: "Mode", options: ["standard", "unrestricted", "autonomous", "soul_agent"], defaultValue: "standard" }] },
  { id: "ai.agent", name: "Agent Executor", moduleId: "whoamisec-gpt", status: "RUNNING", category: "ai", description: "Autonomous agent execution with tool use and planning", params: [{ name: "agent", type: "select", label: "Agent", options: ["orchestrator", "researcher", "coder", "security", "deployer"], defaultValue: "orchestrator" }] },
  { id: "ai.orchestrate", name: "Multi-Agent Orchestrator", moduleId: "whoamisec-gpt", status: "RUNNING", category: "ai", description: "Coordinate multiple AI agents for complex tasks", params: [{ name: "agents", type: "text", label: "Agent List", placeholder: "researcher,coder,tester" }] },
  { id: "ai.self_repair", name: "Self-Repair Engine", moduleId: "whoamisec-gpt", status: "RUNNING", category: "ai", description: "IronClaw self-diagnostic, error recovery, auto-patching", params: [{ name: "target", type: "select", label: "Target", options: ["system", "module", "tool", "all"], defaultValue: "all" }] },
  { id: "ai.tool_build", name: "Dynamic Tool Builder", moduleId: "whoamisec-gpt", status: "RUNNING", category: "ai", description: "Build new tools on-the-fly from natural language descriptions", params: [{ name: "description", type: "text", label: "Tool Description", placeholder: "Describe the tool..." }] },
  { id: "ai.memory", name: "Persistent Memory", moduleId: "whoamisec-gpt", status: "RUNNING", category: "ai", description: "Long-term memory storage, context retrieval, knowledge graph", params: [{ name: "action", type: "select", label: "Action", options: ["store", "retrieve", "search", "clear"], defaultValue: "retrieve" }] },
  { id: "ai.web_search", name: "Web Search Agent", moduleId: "whoamisec-gpt", status: "RUNNING", category: "ai", description: "Real-time internet search with source verification", params: [{ name: "query", type: "text", label: "Search Query", placeholder: "search..." }] },

  // ── MEDIA FORGE (8 tools) ──
  { id: "media.generate", name: "Image Generator", moduleId: "media-forge", status: "RUNNING", category: "media", description: "AI image generation, style transfer, upscaling", params: [{ name: "prompt", type: "text", label: "Prompt", placeholder: "Describe image..." }] },
  { id: "media.detect_deepfake", name: "Deepfake Detector", moduleId: "media-forge", status: "RUNNING", category: "forensics", description: "AI-powered deepfake detection in images and videos", params: [{ name: "confidence", type: "select", label: "Min Confidence", options: ["50%", "70%", "90%", "99%"], defaultValue: "70%" }] },
  { id: "media.stego_encode", name: "Stego Encoder", moduleId: "media-forge", status: "RUNNING", category: "crypto", description: "Hide data in images using LSB, DCT, or spread spectrum", params: [{ name: "method", type: "select", label: "Method", options: ["LSB", "DCT", "spread_spectrum"], defaultValue: "LSB" }] },
  { id: "media.stego_decode", name: "Stego Decoder", moduleId: "media-forge", status: "RUNNING", category: "crypto", description: "Extract hidden data from steganographic images", params: [{ name: "method", type: "select", label: "Method", options: ["LSB", "DCT", "auto_detect"], defaultValue: "auto_detect" }] },
  { id: "media.exif", name: "EXIF Analyzer", moduleId: "media-forge", status: "RUNNING", category: "forensics", description: "Extract and analyze EXIF metadata, GPS coordinates, camera info", params: [{ name: "action", type: "select", label: "Action", options: ["extract", "strip", "modify"], defaultValue: "extract" }] },
  { id: "media.video_gen", name: "Video Generator", moduleId: "media-forge", status: "RUNNING", category: "media", description: "AI video generation, face swap, lip sync", params: [{ name: "type", type: "select", label: "Type", options: ["generate", "face_swap", "lip_sync"], defaultValue: "generate" }] },
  { id: "media.audio_gen", name: "Audio Generator", moduleId: "media-forge", status: "RUNNING", category: "media", description: "Voice cloning, text-to-speech, audio manipulation", params: [{ name: "type", type: "select", label: "Type", options: ["tts", "clone", "modify"], defaultValue: "tts" }] },
  { id: "media.forensics", name: "Media Forensics", moduleId: "media-forge", status: "RUNNING", category: "forensics", description: "Image/video forensic analysis, tampering detection, ELA", params: [{ name: "analysis", type: "select", label: "Analysis", options: ["ELA", "noise", "clone_detect", "full"], defaultValue: "full" }] },

  // ── KERNEL CONFIG (6 tools) ──
  { id: "kernel.config", name: "Kernel Tuner", moduleId: "kernel-config", status: "RUNNING", category: "system", description: "Sysctl parameters, kernel module management, performance tuning", params: [{ name: "action", type: "select", label: "Action", options: ["list", "set", "get", "optimize"], defaultValue: "list" }] },
  { id: "kernel.harden", name: "Hardening Engine", moduleId: "kernel-config", status: "RUNNING", category: "security", description: "CIS benchmarks, STIG compliance, automated hardening", params: [{ name: "standard", type: "select", label: "Standard", options: ["CIS", "STIG", "NIST", "custom"], defaultValue: "CIS" }] },
  { id: "kernel.firewall", name: "Firewall Manager", moduleId: "kernel-config", status: "RUNNING", category: "security", description: "iptables/nftables rule management, zone configuration", params: [{ name: "action", type: "select", label: "Action", options: ["list", "add", "remove", "flush"], defaultValue: "list" }] },
  { id: "kernel.selinux", name: "SELinux Manager", moduleId: "kernel-config", status: "RUNNING", category: "security", description: "SELinux policy management, context labeling, audit", params: [{ name: "mode", type: "select", label: "Mode", options: ["enforcing", "permissive", "disabled", "status"], defaultValue: "status" }] },
  { id: "kernel.audit", name: "Audit System", moduleId: "kernel-config", status: "RUNNING", category: "security", description: "System call auditing, file integrity monitoring, user tracking", params: [{ name: "target", type: "select", label: "Target", options: ["syscalls", "files", "users", "network", "all"], defaultValue: "all" }] },
  { id: "kernel.cgroup", name: "CGroup Manager", moduleId: "kernel-config", status: "RUNNING", category: "system", description: "Resource isolation, CPU/memory limits, process grouping", params: [{ name: "resource", type: "select", label: "Resource", options: ["cpu", "memory", "io", "all"], defaultValue: "all" }] },

  // ── GPT CHAT (5 tools) ──
  { id: "gpt.chat", name: "Chat Interface", moduleId: "gpt-chat", status: "RUNNING", category: "ai", description: "Direct GPT chat with model selection and context management", params: [{ name: "model", type: "select", label: "Model", options: ["manus-gpt", "meta-gpt", "glm5"], defaultValue: "manus-gpt" }] },
  { id: "gpt.stream", name: "Stream Engine", moduleId: "gpt-chat", status: "RUNNING", category: "ai", description: "Real-time streaming response generation", params: [{ name: "temperature", type: "number", label: "Temperature", placeholder: "0.7" }] },
  { id: "gpt.complete", name: "Completion Engine", moduleId: "gpt-chat", status: "RUNNING", category: "ai", description: "Text completion with configurable parameters", params: [{ name: "max_tokens", type: "number", label: "Max Tokens", placeholder: "4096" }] },
  { id: "gpt.vision", name: "Vision Analyzer", moduleId: "gpt-chat", status: "RUNNING", category: "ai", description: "Image analysis, OCR, visual question answering", params: [{ name: "task", type: "select", label: "Task", options: ["analyze", "ocr", "describe", "compare"], defaultValue: "analyze" }] },
  { id: "gpt.code_gen", name: "Code Generator", moduleId: "gpt-chat", status: "RUNNING", category: "ai", description: "Generate code from natural language with test generation", params: [{ name: "language", type: "select", label: "Language", options: ["python", "javascript", "typescript", "rust", "go"], defaultValue: "python" }] },

  // ── IDE (5 tools) ──
  { id: "ide.editor", name: "Editor", moduleId: "ide", status: "RUNNING", category: "dev", description: "Lightweight code editor with multi-tab support", params: [{ name: "theme", type: "select", label: "Theme", options: ["dark", "light", "monokai", "dracula"], defaultValue: "dark" }] },
  { id: "ide.terminal", name: "Integrated Terminal", moduleId: "ide", status: "RUNNING", category: "dev", description: "Built-in terminal with shell access", params: [{ name: "shell", type: "select", label: "Shell", options: ["bash", "zsh", "fish", "sh"], defaultValue: "bash" }] },
  { id: "ide.linter", name: "Linter", moduleId: "ide", status: "RUNNING", category: "dev", description: "Real-time code linting and error detection", params: [{ name: "strict", type: "boolean", label: "Strict Mode" }] },
  { id: "ide.snippets", name: "Snippet Manager", moduleId: "ide", status: "RUNNING", category: "dev", description: "Code snippet library with search and insertion", params: [{ name: "language", type: "select", label: "Language", options: ["all", "python", "javascript", "rust"], defaultValue: "all" }] },
  { id: "ide.diff", name: "Diff Viewer", moduleId: "ide", status: "RUNNING", category: "dev", description: "Side-by-side file comparison and merge tool", params: [{ name: "mode", type: "select", label: "Mode", options: ["side_by_side", "inline", "unified"], defaultValue: "side_by_side" }] },

  // ── SOLANA (8 tools) ──
  { id: "solana.wallet", name: "Wallet Analyzer", moduleId: "solana", status: "RUNNING", category: "blockchain", description: "Wallet balance, transaction history, token holdings analysis", params: [{ name: "address", type: "text", label: "Wallet Address", placeholder: "SOL address" }] },
  { id: "solana.contract", name: "Contract Inspector", moduleId: "solana", status: "RUNNING", category: "blockchain", description: "Smart contract decompilation, vulnerability analysis, audit", params: [{ name: "program_id", type: "text", label: "Program ID", placeholder: "program address" }] },
  { id: "solana.token", name: "Token Tracker", moduleId: "solana", status: "RUNNING", category: "blockchain", description: "SPL token tracking, holder analysis, supply monitoring", params: [{ name: "mint", type: "text", label: "Token Mint", placeholder: "mint address" }] },
  { id: "solana.mev", name: "MEV Scanner", moduleId: "solana", status: "RUNNING", category: "blockchain", description: "MEV opportunity detection, sandwich attack analysis, arbitrage", params: [{ name: "pool", type: "text", label: "Pool Address", placeholder: "pool address" }] },
  { id: "solana.defi", name: "DeFi Dashboard", moduleId: "solana", status: "RUNNING", category: "blockchain", description: "DeFi protocol interaction, yield farming, liquidity analysis", params: [{ name: "protocol", type: "select", label: "Protocol", options: ["raydium", "orca", "jupiter", "marinade", "all"], defaultValue: "all" }] },
  { id: "solana.nft", name: "NFT Analyzer", moduleId: "solana", status: "RUNNING", category: "blockchain", description: "NFT collection analysis, rarity scoring, wash trading detection", params: [{ name: "collection", type: "text", label: "Collection", placeholder: "collection address" }] },
  { id: "solana.tx_trace", name: "Transaction Tracer", moduleId: "solana", status: "RUNNING", category: "blockchain", description: "Transaction flow tracing, fund movement analysis, mixer detection", params: [{ name: "tx_hash", type: "text", label: "TX Hash", placeholder: "transaction signature" }] },
  { id: "solana.validator", name: "Validator Monitor", moduleId: "solana", status: "RUNNING", category: "blockchain", description: "Validator performance, stake distribution, voting analysis", params: [{ name: "validator", type: "text", label: "Validator", placeholder: "vote account" }] },

  // ── DEPLOYER (7 tools) ──
  { id: "deploy.docker", name: "Docker Manager", moduleId: "deployer", status: "RUNNING", category: "devops", description: "Container build, push, run, compose, swarm management", params: [{ name: "action", type: "select", label: "Action", options: ["build", "push", "run", "compose", "swarm"], defaultValue: "build" }] },
  { id: "deploy.k8s", name: "K8s Controller", moduleId: "deployer", status: "RUNNING", category: "devops", description: "Kubernetes deployment, scaling, service mesh, monitoring", params: [{ name: "action", type: "select", label: "Action", options: ["deploy", "scale", "rollback", "status", "logs"], defaultValue: "status" }] },
  { id: "deploy.provision", name: "Server Provisioner", moduleId: "deployer", status: "RUNNING", category: "devops", description: "Cloud server provisioning, Terraform, Ansible automation", params: [{ name: "provider", type: "select", label: "Provider", options: ["aws", "gcp", "azure", "digitalocean"], defaultValue: "aws" }] },
  { id: "deploy.scale", name: "Auto Scaler", moduleId: "deployer", status: "RUNNING", category: "devops", description: "Horizontal/vertical auto-scaling based on metrics", params: [{ name: "metric", type: "select", label: "Scale Metric", options: ["cpu", "memory", "requests", "custom"], defaultValue: "cpu" }] },
  { id: "deploy.monitor", name: "Deploy Monitor", moduleId: "deployer", status: "RUNNING", category: "devops", description: "Deployment health, rollback triggers, canary analysis", params: [{ name: "strategy", type: "select", label: "Strategy", options: ["rolling", "canary", "blue_green"], defaultValue: "rolling" }] },
  { id: "deploy.ci_cd", name: "CI/CD Pipeline", moduleId: "deployer", status: "RUNNING", category: "devops", description: "Build, test, deploy pipelines with GitHub Actions/GitLab CI", params: [{ name: "platform", type: "select", label: "Platform", options: ["github_actions", "gitlab_ci", "jenkins", "circleci"], defaultValue: "github_actions" }] },
  { id: "deploy.ssl", name: "SSL Manager", moduleId: "deployer", status: "RUNNING", category: "devops", description: "Certificate management, Let's Encrypt, renewal automation", params: [{ name: "action", type: "select", label: "Action", options: ["issue", "renew", "revoke", "status"], defaultValue: "status" }] },

  // ── QUANTUM (6 tools) ──
  { id: "quantum.simulate", name: "Quantum Simulator", moduleId: "quantum", status: "RUNNING", category: "quantum", description: "Quantum circuit simulation with up to 30 qubits", params: [{ name: "qubits", type: "number", label: "Qubits", placeholder: "8" }] },
  { id: "quantum.shor", name: "Shor's Algorithm", moduleId: "quantum", status: "RUNNING", category: "quantum", description: "Integer factorization using Shor's algorithm simulation", params: [{ name: "number", type: "number", label: "Number to Factor", placeholder: "15" }] },
  { id: "quantum.grover_sim", name: "Grover's Search", moduleId: "quantum", status: "RUNNING", category: "quantum", description: "Quantum search algorithm simulation for database search", params: [{ name: "items", type: "number", label: "Database Size", placeholder: "1024" }] },
  { id: "quantum.entangle_sim", name: "Entanglement Lab", moduleId: "quantum", status: "RUNNING", category: "quantum", description: "Create and measure entangled qubit pairs, Bell states", params: [{ name: "pairs", type: "number", label: "Pairs", placeholder: "2" }] },
  { id: "quantum.error_correct", name: "Error Correction", moduleId: "quantum", status: "RUNNING", category: "quantum", description: "Quantum error correction codes: Shor, Steane, surface codes", params: [{ name: "code", type: "select", label: "Code", options: ["shor", "steane", "surface", "repetition"], defaultValue: "surface" }] },
  { id: "quantum.random", name: "QRNG", moduleId: "quantum", status: "RUNNING", category: "crypto", description: "Quantum random number generation for cryptographic use", params: [{ name: "bits", type: "number", label: "Bits", placeholder: "256" }] },

  // ── SCANNER (8 tools) ──
  { id: "scan.nmap", name: "Nmap Scanner", moduleId: "scanner", status: "RUNNING", category: "recon", description: "Port scanning, service detection, OS fingerprinting, scripts", params: [{ name: "target", type: "text", label: "Target", placeholder: "IP/CIDR" }, { name: "scan_type", type: "select", label: "Scan Type", options: ["-sS", "-sT", "-sU", "-sV", "-A"], defaultValue: "-sV" }] },
  { id: "scan.masscan", name: "Masscan", moduleId: "scanner", status: "RUNNING", category: "recon", description: "High-speed port scanning across entire internet ranges", params: [{ name: "target", type: "text", label: "Target Range", placeholder: "0.0.0.0/0" }, { name: "rate", type: "number", label: "Packets/sec", placeholder: "10000" }] },
  { id: "scan.cve", name: "CVE Lookup", moduleId: "scanner", status: "RUNNING", category: "intel", description: "CVE database search, CVSS scoring, exploit availability check", params: [{ name: "query", type: "text", label: "CVE/Keyword", placeholder: "CVE-2024-..." }] },
  { id: "scan.exploit_match", name: "Exploit Matcher", moduleId: "scanner", status: "RUNNING", category: "offensive", description: "Match discovered services to known exploits", params: [{ name: "service", type: "text", label: "Service", placeholder: "apache/2.4.49" }] },
  { id: "scan.fingerprint", name: "Fingerprinter", moduleId: "scanner", status: "RUNNING", category: "recon", description: "Web app fingerprinting, technology detection, WAF identification", params: [{ name: "url", type: "text", label: "URL", placeholder: "https://target.com" }] },
  { id: "scan.ssl_check", name: "SSL Checker", moduleId: "scanner", status: "RUNNING", category: "security", description: "SSL/TLS configuration analysis, cipher suite check, cert validation", params: [{ name: "host", type: "text", label: "Host", placeholder: "example.com" }] },
  { id: "scan.dns_recon", name: "DNS Recon", moduleId: "scanner", status: "RUNNING", category: "recon", description: "DNS enumeration, zone transfer, cache snooping", params: [{ name: "domain", type: "text", label: "Domain", placeholder: "example.com" }] },
  { id: "scan.vuln_assess", name: "Vulnerability Assessor", moduleId: "scanner", status: "RUNNING", category: "security", description: "Automated vulnerability assessment with severity scoring", params: [{ name: "target", type: "text", label: "Target", placeholder: "IP or URL" }] },

  // ── S3 BUCKETS (7 tools) ──
  { id: "s3.enumerate", name: "Bucket Enumerator", moduleId: "s3-buckets", status: "RUNNING", category: "cloud", description: "Discover publicly accessible S3 buckets by keyword/company", params: [{ name: "keyword", type: "text", label: "Keyword", placeholder: "company name" }] },
  { id: "s3.misconfig", name: "Misconfig Scanner", moduleId: "s3-buckets", status: "RUNNING", category: "cloud", description: "Detect misconfigured bucket permissions, public access", params: [{ name: "bucket", type: "text", label: "Bucket Name", placeholder: "bucket-name" }] },
  { id: "s3.exfil", name: "Data Exfiltrator", moduleId: "s3-buckets", status: "RUNNING", category: "cloud", description: "Download and catalog accessible bucket contents", params: [{ name: "bucket", type: "text", label: "Bucket", placeholder: "bucket-name" }, { name: "filter", type: "text", label: "File Filter", placeholder: "*.sql" }] },
  { id: "s3.acl", name: "ACL Analyzer", moduleId: "s3-buckets", status: "RUNNING", category: "cloud", description: "Analyze bucket ACLs, policies, cross-account access", params: [{ name: "bucket", type: "text", label: "Bucket", placeholder: "bucket-name" }] },
  { id: "s3.upload", name: "Upload Manager", moduleId: "s3-buckets", status: "RUNNING", category: "cloud", description: "Upload files to accessible buckets, test write permissions", params: [{ name: "bucket", type: "text", label: "Bucket", placeholder: "bucket-name" }] },
  { id: "s3.azure_blob", name: "Azure Blob Scanner", moduleId: "s3-buckets", status: "RUNNING", category: "cloud", description: "Scan Azure Blob Storage for misconfigurations", params: [{ name: "account", type: "text", label: "Storage Account", placeholder: "account name" }] },
  { id: "s3.gcs_scan", name: "GCS Scanner", moduleId: "s3-buckets", status: "RUNNING", category: "cloud", description: "Google Cloud Storage bucket enumeration and access testing", params: [{ name: "project", type: "text", label: "Project", placeholder: "project-id" }] },

  // ── BLACKHAT (8 tools) ──
  { id: "blackhat.metasploit", name: "Metasploit", moduleId: "blackhat", status: "RUNNING", category: "offensive", description: "Metasploit Framework integration, module search, exploit execution", params: [{ name: "module", type: "text", label: "Module", placeholder: "exploit/..." }] },
  { id: "blackhat.set", name: "Social Engineering Toolkit", moduleId: "blackhat", status: "RUNNING", category: "offensive", description: "Phishing campaigns, credential harvesting, USB attacks", params: [{ name: "attack", type: "select", label: "Attack Type", options: ["spear_phish", "web_clone", "usb_hid", "qr_code"], defaultValue: "spear_phish" }] },
  { id: "blackhat.phish", name: "Phishing Framework", moduleId: "blackhat", status: "RUNNING", category: "offensive", description: "Email phishing, landing page cloning, tracking pixels", params: [{ name: "template", type: "select", label: "Template", options: ["office365", "google", "linkedin", "custom"], defaultValue: "office365" }] },
  { id: "blackhat.harvest", name: "Credential Harvester", moduleId: "blackhat", status: "RUNNING", category: "offensive", description: "Capture credentials from cloned login pages", params: [{ name: "target_site", type: "text", label: "Target Site", placeholder: "https://..." }] },
  { id: "blackhat.bruteforce", name: "Brute Forcer", moduleId: "blackhat", status: "RUNNING", category: "offensive", description: "Password brute-force, dictionary attacks, rule-based cracking", params: [{ name: "service", type: "select", label: "Service", options: ["ssh", "ftp", "http", "rdp", "smb", "mysql"], defaultValue: "ssh" }, { name: "wordlist", type: "select", label: "Wordlist", options: ["rockyou", "custom", "generated"], defaultValue: "rockyou" }] },
  { id: "blackhat.hashcat", name: "Hashcat", moduleId: "blackhat", status: "RUNNING", category: "offensive", description: "GPU-accelerated hash cracking, rule generation, mask attacks", params: [{ name: "hash_type", type: "select", label: "Hash Type", options: ["MD5", "SHA1", "SHA256", "NTLM", "bcrypt"], defaultValue: "NTLM" }] },
  { id: "blackhat.wifi", name: "WiFi Attacker", moduleId: "blackhat", status: "RUNNING", category: "offensive", description: "WPA/WPA2 cracking, evil twin, deauth, PMKID capture", params: [{ name: "attack", type: "select", label: "Attack", options: ["handshake", "pmkid", "evil_twin", "deauth"], defaultValue: "handshake" }] },
  { id: "blackhat.keylogger", name: "Keylogger", moduleId: "blackhat", status: "RUNNING", category: "offensive", description: "Keystroke capture, clipboard monitoring, screenshot capture", params: [{ name: "mode", type: "select", label: "Mode", options: ["keyboard", "clipboard", "screenshot", "all"], defaultValue: "all" }] },

  // ── LAZARUS APT (7 tools) ──
  { id: "apt.emulate", name: "APT Emulator", moduleId: "lazarus-apt", status: "RUNNING", category: "intel", description: "Emulate known APT group TTPs for red team exercises", params: [{ name: "group", type: "select", label: "APT Group", options: ["Lazarus", "APT28", "APT29", "Equation", "Turla"], defaultValue: "Lazarus" }] },
  { id: "apt.campaign", name: "Campaign Manager", moduleId: "lazarus-apt", status: "RUNNING", category: "intel", description: "Multi-phase attack campaign planning and execution", params: [{ name: "phase", type: "select", label: "Phase", options: ["recon", "weaponize", "deliver", "exploit", "install", "c2", "action"], defaultValue: "recon" }] },
  { id: "apt.ttps", name: "TTP Library", moduleId: "lazarus-apt", status: "RUNNING", category: "intel", description: "MITRE ATT&CK technique library with implementation guides", params: [{ name: "tactic", type: "select", label: "Tactic", options: ["initial_access", "execution", "persistence", "privilege_escalation", "defense_evasion", "credential_access", "discovery", "lateral_movement", "collection", "exfiltration"], defaultValue: "initial_access" }] },
  { id: "apt.mitre", name: "MITRE Mapper", moduleId: "lazarus-apt", status: "RUNNING", category: "intel", description: "Map observed techniques to MITRE ATT&CK framework", params: [{ name: "technique_id", type: "text", label: "Technique ID", placeholder: "T1059.001" }] },
  { id: "apt.intel", name: "Threat Intel Feed", moduleId: "lazarus-apt", status: "RUNNING", category: "intel", description: "Real-time threat intelligence feeds, IOC management", params: [{ name: "source", type: "select", label: "Source", options: ["all", "alienvault", "virustotal", "shodan", "custom"], defaultValue: "all" }] },
  { id: "apt.ioc_scan", name: "IOC Scanner", moduleId: "lazarus-apt", status: "RUNNING", category: "intel", description: "Scan systems for known Indicators of Compromise", params: [{ name: "ioc_type", type: "select", label: "IOC Type", options: ["hash", "ip", "domain", "url", "all"], defaultValue: "all" }] },
  { id: "apt.report_gen", name: "Report Generator", moduleId: "lazarus-apt", status: "RUNNING", category: "intel", description: "Generate threat assessment and incident reports", params: [{ name: "format", type: "select", label: "Format", options: ["pdf", "html", "json", "stix"], defaultValue: "pdf" }] },

  // ── BURPSUITE (8 tools) ──
  { id: "burp.proxy", name: "Proxy Interceptor", moduleId: "burpsuite", status: "RUNNING", category: "web", description: "HTTP/HTTPS proxy with request/response interception and modification", params: [{ name: "port", type: "number", label: "Proxy Port", placeholder: "8080" }] },
  { id: "burp.scan", name: "Active Scanner", moduleId: "burpsuite", status: "RUNNING", category: "web", description: "Automated vulnerability scanning: SQLi, XSS, SSRF, XXE", params: [{ name: "target", type: "text", label: "Target URL", placeholder: "https://..." }, { name: "scope", type: "select", label: "Scope", options: ["url_only", "domain", "subdomain"], defaultValue: "domain" }] },
  { id: "burp.intruder", name: "Intruder", moduleId: "burpsuite", status: "RUNNING", category: "web", description: "Automated payload injection, fuzzing, brute-force attacks", params: [{ name: "attack_type", type: "select", label: "Attack Type", options: ["sniper", "battering_ram", "pitchfork", "cluster_bomb"], defaultValue: "sniper" }] },
  { id: "burp.repeater", name: "Repeater", moduleId: "burpsuite", status: "RUNNING", category: "web", description: "Manual request modification and replay for testing", params: [{ name: "method", type: "select", label: "Method", options: ["GET", "POST", "PUT", "DELETE", "PATCH"], defaultValue: "GET" }] },
  { id: "burp.sequencer", name: "Sequencer", moduleId: "burpsuite", status: "RUNNING", category: "web", description: "Token randomness analysis, session token quality testing", params: [{ name: "samples", type: "number", label: "Samples", placeholder: "1000" }] },
  { id: "burp.decoder", name: "Decoder", moduleId: "burpsuite", status: "RUNNING", category: "web", description: "Encode/decode: Base64, URL, HTML, hex, gzip, JWT", params: [{ name: "encoding", type: "select", label: "Encoding", options: ["base64", "url", "html", "hex", "jwt", "auto"], defaultValue: "auto" }] },
  { id: "burp.collaborator", name: "Collaborator", moduleId: "burpsuite", status: "RUNNING", category: "web", description: "Out-of-band interaction detection for blind vulnerabilities", params: [{ name: "protocol", type: "select", label: "Protocol", options: ["http", "dns", "smtp", "all"], defaultValue: "all" }] },
  { id: "burp.crawler", name: "Web Crawler", moduleId: "burpsuite", status: "RUNNING", category: "web", description: "Intelligent web crawling with form submission and JS execution", params: [{ name: "depth", type: "number", label: "Crawl Depth", placeholder: "5" }] },

  // ── OWASP ZAP (7 tools) ──
  { id: "zap.scan", name: "ZAP Scanner", moduleId: "owasp-zap", status: "RUNNING", category: "web", description: "Passive and active scanning for OWASP Top 10 vulnerabilities", params: [{ name: "target", type: "text", label: "Target", placeholder: "https://..." }, { name: "mode", type: "select", label: "Mode", options: ["passive", "active", "full"], defaultValue: "active" }] },
  { id: "zap.fuzz", name: "Fuzzer", moduleId: "owasp-zap", status: "RUNNING", category: "web", description: "Input fuzzing with custom payloads, mutation, and generation", params: [{ name: "fuzz_type", type: "select", label: "Fuzz Type", options: ["mutation", "generation", "dictionary"], defaultValue: "mutation" }] },
  { id: "zap.spider", name: "Spider", moduleId: "owasp-zap", status: "RUNNING", category: "web", description: "Web application spidering, sitemap generation, link discovery", params: [{ name: "url", type: "text", label: "Start URL", placeholder: "https://..." }] },
  { id: "zap.api_test", name: "API Tester", moduleId: "owasp-zap", status: "RUNNING", category: "web", description: "REST/GraphQL API security testing, schema validation", params: [{ name: "spec_url", type: "text", label: "API Spec URL", placeholder: "https://.../openapi.json" }] },
  { id: "zap.auth_test", name: "Auth Tester", moduleId: "owasp-zap", status: "RUNNING", category: "web", description: "Authentication bypass, session management, CSRF testing", params: [{ name: "test", type: "select", label: "Test", options: ["auth_bypass", "session", "csrf", "jwt", "all"], defaultValue: "all" }] },
  { id: "zap.ajax_spider", name: "AJAX Spider", moduleId: "owasp-zap", status: "RUNNING", category: "web", description: "JavaScript-aware crawling for modern web applications", params: [{ name: "browser", type: "select", label: "Browser", options: ["chrome", "firefox", "htmlunit"], defaultValue: "chrome" }] },
  { id: "zap.report", name: "Report Generator", moduleId: "owasp-zap", status: "RUNNING", category: "web", description: "Generate security assessment reports in multiple formats", params: [{ name: "format", type: "select", label: "Format", options: ["html", "pdf", "xml", "json"], defaultValue: "html" }] },

  // ── TERMINAL CONSOLE (6 tools) ──
  { id: "terminal.exec", name: "Command Executor", moduleId: "terminal-console", status: "RUNNING", category: "system", description: "Execute system commands with output capture and error handling", params: [{ name: "command", type: "text", label: "Command", placeholder: "ls -la" }] },
  { id: "terminal.script", name: "Script Runner", moduleId: "terminal-console", status: "RUNNING", category: "system", description: "Execute shell scripts with environment variable support", params: [{ name: "interpreter", type: "select", label: "Interpreter", options: ["bash", "python", "node", "ruby"], defaultValue: "bash" }] },
  { id: "terminal.pipe", name: "Pipe Builder", moduleId: "terminal-console", status: "RUNNING", category: "system", description: "Build complex command pipelines with visual flow", params: [{ name: "commands", type: "text", label: "Pipeline", placeholder: "cmd1 | cmd2 | cmd3" }] },
  { id: "terminal.cron", name: "Cron Manager", moduleId: "terminal-console", status: "RUNNING", category: "system", description: "Schedule and manage cron jobs, task automation", params: [{ name: "action", type: "select", label: "Action", options: ["list", "add", "remove", "edit"], defaultValue: "list" }] },
  { id: "terminal.ssh", name: "SSH Client", moduleId: "terminal-console", status: "RUNNING", category: "network", description: "SSH connection manager with key management and tunneling", params: [{ name: "host", type: "text", label: "Host", placeholder: "user@host" }] },
  { id: "terminal.file_manager", name: "File Manager", moduleId: "terminal-console", status: "RUNNING", category: "system", description: "File browsing, editing, permissions, search", params: [{ name: "path", type: "text", label: "Path", placeholder: "/" }] },

  // ── KIMIKUKIU REPOS (51 tools) ──
  { id: "kk.imagereward", name: "ImageReward", moduleId: "kimikukiu-ai", status: "RUNNING", category: "ai-ml", description: "AI model for scoring and ranking generated images based on human preference", params: [{ name: "model_path", type: "text", label: "Model Path", placeholder: "" }, { name: "image_url", type: "text", label: "Image Url", placeholder: "" }, { name: "batch_size", type: "number", label: "Batch Size", placeholder: "" }] },
  { id: "kk.cogvideo", name: "CogVideo", moduleId: "kimikukiu-ai", status: "RUNNING", category: "ai-ml", description: "A text and image to video generation model.", params: [{ name: "model_name", type: "text", label: "Model Name", placeholder: "" }, { name: "prompt", type: "text", label: "Prompt", placeholder: "" }, { name: "input_image", type: "text", label: "Input Image", placeholder: "" }] },
  { id: "kk.satan_stealer", name: "Satan-Stealer", moduleId: "kimikukiu-stealer", status: "RUNNING", category: "stealer", description: "A tool for stealing Discord information, passwords, cookies, files, and crypto wallets.", params: [{ name: "webhook_url", type: "text", label: "Webhook Url", placeholder: "" }, { name: "telegram_token", type: "text", label: "Telegram Token", placeholder: "" }, { name: "chat_id", type: "text", label: "Chat Id", placeholder: "" }] },
  { id: "kk.cryptonote_easy_miner", name: "cryptonote-easy-miner", moduleId: "kimikukiu-crypto", status: "RUNNING", category: "crypto", description: "Simplify mining with this C# app for Windows, streamlining setup of CryptoNote mining without command-line hassle.", params: [{ name: "mining_pool_addresse", type: "text", label: "Mining Pool Addresse", placeholder: "" }, { name: "hash_rates", type: "number", label: "Hash Rates", placeholder: "" }] },
  { id: "kk.labexploit", name: "LabExploit", moduleId: "kimikukiu-exploit", status: "RUNNING", category: "exploitation", description: "A security research tool to develop and analyze exploits with built-in safety controls for authorized use.", params: [{ name: "target_host", type: "text", label: "Target Host", placeholder: "" }, { name: "exploit_module", type: "text", label: "Exploit Module", placeholder: "" }, { name: "payload_options", type: "text", label: "Payload Options", placeholder: "" }] },
  { id: "kk.cryptocurrency_stealer", name: "Cryptocurrency-Stealer", moduleId: "kimikukiu-stealer", status: "RUNNING", category: "stealer", description: "A tool that replaces specific cryptocurrency addresses with a user's own addresses.", params: [{ name: "user_cryptocurrency_", type: "text", label: "User Cryptocurrency ", placeholder: "" }] },
  { id: "kk.aiscan_n", name: "AiScan-N", moduleId: "kimikukiu-security", status: "RUNNING", category: "security", description: "AiScan-N is an AI-based automation tool for penetration testing, designed for both businesses and individuals to easily ", params: [{ name: "target_urlip", type: "text", label: "Target Urlip", placeholder: "" }, { name: "scan_type", type: "select", label: "Scan Type", options: ["default", "custom"], defaultValue: "default" }, { name: "report_path", type: "text", label: "Report Path", placeholder: "" }] },
  { id: "kk.p4rs3lt0ngv3", name: "P4RS3LT0NGV3", moduleId: "kimikukiu-webtools", status: "RUNNING", category: "web-tools", description: "A powerful web-based text transformation and steganography tool that can encode/decode text in 79+ different languages, ", params: [{ name: "input_text", type: "text", label: "Input Text", placeholder: "" }, { name: "transformation", type: "select", label: "Transformation", options: ["default", "custom"], defaultValue: "default" }, { name: "cipher_key", type: "text", label: "Cipher Key", placeholder: "" }] },
  { id: "kk.realvideo", name: "RealVideo", moduleId: "kimikukiu-video", status: "RUNNING", category: "video", description: "A real-time streaming conversational video system that transforms text interactions into continuous, high-fidelity video", params: [{ name: "zai_api_key", type: "text", label: "Zai Api Key", placeholder: "" }, { name: "path_to_your_model", type: "text", label: "Path To Your Model", placeholder: "" }, { name: "cuda_visible_devices", type: "text", label: "Cuda Visible Devices", placeholder: "" }] },
  { id: "kk.glm_image", name: "GLM-Image", moduleId: "kimikukiu-ai", status: "RUNNING", category: "ai-ml", description: "GLM-Image is an image generation model that uses a hybrid autoregressive and diffusion decoder architecture to generate ", params: [{ name: "model_name", type: "text", label: "Model Name", placeholder: "" }, { name: "input_text", type: "text", label: "Input Text", placeholder: "" }, { name: "image_path", type: "text", label: "Image Path", placeholder: "" }] },
  { id: "kk.glm_tts", name: "GLM-TTS", moduleId: "kimikukiu-voice", status: "RUNNING", category: "voice", description: "A high-quality text-to-speech (TTS) synthesis system based on large language models, supporting zero-shot voice cloning ", params: [{ name: "data", type: "text", label: "Data", placeholder: "" }, { name: "exp_name", type: "text", label: "Exp Name", placeholder: "" }, { name: "use_cache", type: "boolean", label: "Use Cache" }] },
  { id: "kk.leakhub", name: "LEAKHUB", moduleId: "kimikukiu-llm", status: "RUNNING", category: "llm", description: "A community hub for crowd-sourced system prompt leak verification.", params: [{ name: "targetname", type: "text", label: "Targetname", placeholder: "" }, { name: "provider", type: "text", label: "Provider", placeholder: "" }, { name: "targettype", type: "select", label: "Targettype", options: ["default", "custom"], defaultValue: "default" }] },
  { id: "kk.glm_v", name: "GLM-V", moduleId: "kimikukiu-llm", status: "RUNNING", category: "llm", description: "An open-source vision-language model (VLM) for complex multimodal reasoning, long-context understanding, and multimodal ", params: [{ name: "model_path", type: "text", label: "Model Path", placeholder: "" }, { name: "tensor_parallel_size", type: "number", label: "Tensor Parallel Size", placeholder: "" }, { name: "enable_thinking", type: "boolean", label: "Enable Thinking" }] },
  { id: "kk.web_cloner", name: "WEB-CLONER", moduleId: "kimikukiu-webtools", status: "RUNNING", category: "web-tools", description: "A tool to clone websites for offline browsing or phishing.", params: [{ name: "target_url", type: "text", label: "Target Url", placeholder: "" }, { name: "output_directory", type: "text", label: "Output Directory", placeholder: "" }] },
  { id: "kk.reth", name: "reth", moduleId: "kimikukiu-blockchain", status: "RUNNING", category: "blockchain", description: "A modular, contributor-friendly, and blazing-fast implementation of the Ethereum protocol in Rust.", params: [{ name: "__config", type: "text", label: "  Config", placeholder: "" }, { name: "__datadir", type: "text", label: "  Datadir", placeholder: "" }, { name: "chain", type: "text", label: "Chain", placeholder: "" }] },
  { id: "kk.glm_asr", name: "GLM-ASR", moduleId: "kimikukiu-voice", status: "RUNNING", category: "voice", description: "A robust, open-source speech recognition model with 1.5B parameters, designed for real-world complexity and outperformin", params: [{ name: "model_path", type: "text", label: "Model Path", placeholder: "" }, { name: "audio_url", type: "text", label: "Audio Url", placeholder: "" }, { name: "device", type: "select", label: "Device", options: ["default", "custom"], defaultValue: "default" }] },
  { id: "kk.agentbench", name: "AgentBench", moduleId: "kimikukiu-llm", status: "RUNNING", category: "llm", description: "A comprehensive benchmark to evaluate LLMs as agents across a diverse spectrum of different environments.", params: [{ name: "openai_api_key", type: "text", label: "Openai Api Key", placeholder: "" }, { name: "agent", type: "text", label: "Agent", placeholder: "" }, { name: "config", type: "text", label: "Config", placeholder: "" }] },
  { id: "kk.vllm", name: "vllm", moduleId: "kimikukiu-llm", status: "RUNNING", category: "llm", description: "A high-throughput and memory-efficient inference and serving engine for LLMs.", params: [{ name: "model", type: "text", label: "Model", placeholder: "" }, { name: "pipeline", type: "text", label: "Pipeline", placeholder: "" }, { name: "host", type: "text", label: "Host", placeholder: "" }] },
  { id: "kk.carr", name: "CaRR", moduleId: "kimikukiu-ai", status: "RUNNING", category: "ai-ml", description: "A framework for robust reinforcement learning for deep search agents with citation-aware rubric rewards.", params: [{ name: "backbone_model", type: "text", label: "Backbone Model", placeholder: "" }, { name: "training_data", type: "text", label: "Training Data", placeholder: "" }, { name: "rl_framework", type: "text", label: "Rl Framework", placeholder: "" }] },
  { id: "kk.xgpt_wormgpt", name: "XGPT-WormGPT", moduleId: "kimikukiu-exploit", status: "RUNNING", category: "exploitation", description: "A project that provides prompts to make Large Language Models generate malicious content and perform illegal activities.", params: [{ name: "target_description", type: "text", label: "Target Description", placeholder: "" }, { name: "desired_malicious_ou", type: "text", label: "Desired Malicious Ou", placeholder: "" }, { name: "llm_model", type: "text", label: "Llm Model", placeholder: "" }] },
  { id: "kk.glm_5", name: "GLM-5", moduleId: "kimikukiu-llm", status: "RUNNING", category: "llm", description: "A large language model for complex systems engineering and long-horizon agentic tasks.", params: [{ name: "tensor_parallel_size", type: "number", label: "Tensor Parallel Size", placeholder: "" }, { name: "gpu_memory_utilizati", type: "number", label: "Gpu Memory Utilizati", placeholder: "" }, { name: "model_path", type: "text", label: "Model Path", placeholder: "" }] },
  { id: "kk.glm_4_5", name: "GLM-4.5", moduleId: "kimikukiu-llm", status: "RUNNING", category: "llm", description: "The GLM-4.5 series models are foundation models designed for intelligent agents, unifying reasoning, coding, and intelli", params: [{ name: "model", type: "text", label: "Model", placeholder: "" }, { name: "precision", type: "select", label: "Precision", options: ["default", "custom"], defaultValue: "default" }, { name: "gpu_type_and_count", type: "text", label: "Gpu Type And Count", placeholder: "" }] },
  { id: "kk.glm_simple_evals", name: "glm-simple-evals", moduleId: "kimikukiu-llm", status: "RUNNING", category: "llm", description: "An evaluation toolkit for large language models, forked from zai-org/glm-simple-evals and based on OpenAI's simple-evals", params: [{ name: "model_name", type: "text", label: "Model Name", placeholder: "" }, { name: "backbone", type: "text", label: "Backbone", placeholder: "" }, { name: "zai_api_key", type: "text", label: "Zai Api Key", placeholder: "" }] },
  { id: "kk.hexstrike_ai", name: "Hexstrike-AI", moduleId: "kimikukiu-security", status: "RUNNING", category: "security", description: "HexStrike AI MCP Agents is an advanced MCP server that lets AI agents autonomously run 150+ cybersecurity tools for auto", params: [{ name: "target", type: "text", label: "Target", placeholder: "" }, { name: "analysis_type", type: "text", label: "Analysis Type", placeholder: "" }, { name: "port", type: "number", label: "Port", placeholder: "" }] },
  { id: "kk.w0rm_gpt", name: "W0rm-Gpt", moduleId: "kimikukiu-ai", status: "RUNNING", category: "ai-ml", description: "An advanced AI chat application for research and development, providing an unrestricted environment for AI interaction a", params: [{ name: "email", type: "text", label: "Email", placeholder: "" }, { name: "password", type: "text", label: "Password", placeholder: "" }, { name: "prompt", type: "text", label: "Prompt", placeholder: "" }] },
  { id: "kk.worm_ai", name: "worm-ai", moduleId: "kimikukiu-llm", status: "RUNNING", category: "llm", description: "A command-line interface (CLI) for interacting with LLMs via the OpenRouter API, featuring multi-language support and cu", params: [{ name: "api_key", type: "text", label: "Api Key", placeholder: "" }, { name: "model", type: "text", label: "Model", placeholder: "" }, { name: "language", type: "select", label: "Language", options: ["default", "custom"], defaultValue: "default" }] },
  { id: "kk.bitlockmove", name: "BitlockMove", moduleId: "kimikukiu-exploit", status: "RUNNING", category: "exploitation", description: "A proof-of-concept for lateral movement in a network by abusing BitLocker's DCOM interfaces and COM hijacking.", params: [{ name: "mode", type: "text", label: "Mode", placeholder: "" }, { name: "target", type: "text", label: "Target", placeholder: "" }, { name: "dllpath", type: "text", label: "Dllpath", placeholder: "" }] },
  { id: "kk.pentagi", name: "pentagi", moduleId: "kimikukiu-pentest", status: "RUNNING", category: "pentesting", description: "PentAGI is an innovative tool for automated security testing that leverages cutting-edge artificial intelligence technol", params: [{ name: "open_ai_key", type: "text", label: "Open Ai Key", placeholder: "" }, { name: "anthropic_api_key", type: "text", label: "Anthropic Api Key", placeholder: "" }, { name: "google_api_key", type: "text", label: "Google Api Key", placeholder: "" }] },
  { id: "kk.cve_2025_43300", name: "CVE-2025-43300", moduleId: "kimikukiu-exploit", status: "RUNNING", category: "exploitation", description: "A proof-of-concept for CVE-2025-43300, a zero-click memory corruption vulnerability in iOS and macOS caused by inconsist", params: [{ name: "input_file", type: "text", label: "Input File", placeholder: "" }, { name: "output_file", type: "text", label: "Output File", placeholder: "" }, { name: "offset", type: "number", label: "Offset", placeholder: "" }] },
  { id: "kk.autotemp", name: "AutoTemp", moduleId: "kimikukiu-llm", status: "RUNNING", category: "llm", description: "A trial-and-error approach to temperature optimization for LLMs that runs the same prompt at many temperatures and selec", params: [{ name: "openai_api_key", type: "text", label: "Openai Api Key", placeholder: "" }, { name: "alt_temps", type: "text", label: "Alt Temps", placeholder: "" }, { name: "model_version", type: "text", label: "Model Version", placeholder: "" }] },
  { id: "kk.mcf", name: "MCF", moduleId: "kimikukiu-ai", status: "RUNNING", category: "ai-ml", description: "A framework to enable text-based LLMs to perform multimodal emotional causality analysis by transforming video, audio, a", params: [{ name: "input_file", type: "text", label: "Input File", placeholder: "" }, { name: "api_key", type: "text", label: "Api Key", placeholder: "" }, { name: "model_path", type: "text", label: "Model Path", placeholder: "" }] },
  { id: "kk.linkscrapper", name: "LinkScrapper", moduleId: "kimikukiu-webtools", status: "RUNNING", category: "web-tools", description: "A Python tool for extracting and visualizing endpoints from JavaScript files, web pages, or Burp Suite exports.", params: [{ name: "input", type: "text", label: "Input", placeholder: "" }, { name: "output", type: "text", label: "Output", placeholder: "" }, { name: "regex", type: "text", label: "Regex", placeholder: "" }] },
  { id: "kk.sqlforce", name: "sqlforce", moduleId: "kimikukiu-pentest", status: "RUNNING", category: "pentesting", description: "Sends a series of SQL-like payloads to target URLs in order to force SQL errors and record server responses.", params: [{ name: "target_urls", type: "text", label: "Target Urls", placeholder: "" }, { name: "payload_file", type: "text", label: "Payload File", placeholder: "" }, { name: "output_file", type: "text", label: "Output File", placeholder: "" }] },
  { id: "kk.kestra", name: "kestra", moduleId: "kimikukiu-workflow", status: "RUNNING", category: "workflow", description: "Kestra is an open-source, event-driven orchestration platform that makes both scheduled and event-driven workflows easy.", params: [{ name: "id", type: "text", label: "Id", placeholder: "" }, { name: "namespace", type: "text", label: "Namespace", placeholder: "" }, { name: "tasks", type: "text", label: "Tasks", placeholder: "" }] },
  { id: "kk.kaleido", name: "Kaleido", moduleId: "kimikukiu-video", status: "RUNNING", category: "video", description: "Kaleido is an open-sourced multi-subject reference video generation model, enabling controllable, high-fidelity video sy", params: [{ name: "base", type: "text", label: "Base", placeholder: "" }, { name: "config", type: "text", label: "Config", placeholder: "" }, { name: "prompt", type: "text", label: "Prompt", placeholder: "" }] },
  { id: "kk.open_autoglm", name: "Open-AutoGLM", moduleId: "kimikukiu-llm", status: "RUNNING", category: "llm", description: "An open-source phone agent model and framework that uses multimodal AI to understand and automate tasks on Android and H", params: [{ name: "base_url", type: "text", label: "Base Url", placeholder: "" }, { name: "model", type: "text", label: "Model", placeholder: "" }, { name: "apikey", type: "text", label: "Apikey", placeholder: "" }] },
  { id: "kk.method_c", name: "method_c", moduleId: "kimikukiu-ddos", status: "RUNNING", category: "ddos", description: "A tool for launching DDoS attacks, as suggested by the repository name and the single file ddos_methodC.zip.", params: [{ name: "target_url", type: "text", label: "Target Url", placeholder: "" }, { name: "attack_method", type: "select", label: "Attack Method", options: ["default", "custom"], defaultValue: "default" }, { name: "duration", type: "number", label: "Duration", placeholder: "" }] },
  { id: "kk.tls", name: "tls", moduleId: "kimikukiu-security", status: "RUNNING", category: "security", description: "A project for implementing or testing Transport Layer Security (TLS) protocols.", params: [{ name: "target_host", type: "text", label: "Target Host", placeholder: "" }, { name: "target_port", type: "number", label: "Target Port", placeholder: "" }, { name: "certificate_file", type: "text", label: "Certificate File", placeholder: "" }] },
  { id: "kk.hajime_ag", name: "Hajime-AG", moduleId: "kimikukiu-security", status: "RUNNING", category: "security", description: "A peer-to-peer botnet that targets and secures vulnerable IoT devices by closing open ports.", params: [{ name: "target_ip_ranges", type: "text", label: "Target Ip Ranges", placeholder: "" }, { name: "password_dictionary_", type: "text", label: "Password Dictionary ", placeholder: "" }, { name: "p2p_bootstrap_nodes", type: "text", label: "P2P Bootstrap Nodes", placeholder: "" }] },
  { id: "kk.executor_ddos", name: "EXECUTOR-DDOS", moduleId: "kimikukiu-ddos", status: "RUNNING", category: "ddos", description: "A tool for launching Denial of Service (DoS) attacks against servers for testing purposes.", params: [{ name: "target_server", type: "text", label: "Target Server", placeholder: "" }, { name: "attack_method", type: "text", label: "Attack Method", placeholder: "" }] },
  { id: "kk.thegodofai", name: "TheGodOfAI", moduleId: "kimikukiu-ai", status: "RUNNING", category: "ai-ml", description: "A comprehensive and powerful AI framework, likely designed to handle a wide array of artificial intelligence tasks.", params: [{ name: "task_description", type: "text", label: "Task Description", placeholder: "" }, { name: "model_preference", type: "select", label: "Model Preference", options: ["default", "custom"], defaultValue: "default" }, { name: "api_key", type: "text", label: "Api Key", placeholder: "" }] },
  { id: "kk.openclaw_android_assistant", name: "openclaw-android-assistant", moduleId: "kimikukiu-ai", status: "RUNNING", category: "ai-ml", description: "A self-contained Android APK that bundles OpenClaw and OpenAI Codex CLI with a complete Linux environment, allowing two ", params: [{ name: "openai_account", type: "text", label: "Openai Account", placeholder: "" }, { name: "targetsdk", type: "text", label: "Targetsdk", placeholder: "" }, { name: "https_proxy", type: "text", label: "Https Proxy", placeholder: "" }] },
  { id: "kk.whm_un1c", name: "whm-un1c", moduleId: "kimikukiu-security", status: "RUNNING", category: "security", description: "A quantum intelligence platform with a Botnet C2, LISP engine, MIL-SPEC tactical capabilities, and over 30 security tool", params: [{ name: "c2_host", type: "text", label: "C2 Host", placeholder: "" }, { name: "target_host", type: "text", label: "Target Host", placeholder: "" }, { name: "gemini_api_key", type: "text", label: "Gemini Api Key", placeholder: "" }] },
  { id: "kk.promptfoo", name: "promptfoo", moduleId: "kimikukiu-llm", status: "RUNNING", category: "llm", description: "A tool for testing and evaluating language model prompts, agents, and RAGs, including AI red teaming, pentesting, and vu", params: [{ name: "prompts", type: "text", label: "Prompts", placeholder: "" }, { name: "providers", type: "text", label: "Providers", placeholder: "" }, { name: "tests", type: "text", label: "Tests", placeholder: "" }] },
  { id: "kk.install_setup", name: "Install-setup", moduleId: "kimikukiu-automation", status: "RUNNING", category: "automation", description: "A project that provides scripts and configurations for automating the installation and setup of software.", params: [{ name: "target_software", type: "text", label: "Target Software", placeholder: "" }, { name: "configuration_file_p", type: "text", label: "Configuration File P", placeholder: "" }, { name: "installation_directo", type: "text", label: "Installation Directo", placeholder: "" }] },
  { id: "kk.kaligpt", name: "KaliGPT", moduleId: "kimikukiu-pentest", status: "RUNNING", category: "pentesting", description: "KaliGPT is an agentic AI assistant for the Linux CLI, fine-tuned for ethical hacking and cybersecurity to make workflows", params: [{ name: "api_keys", type: "text", label: "Api Keys", placeholder: "" }, { name: "ai_model", type: "select", label: "Ai Model", options: ["default", "custom"], defaultValue: "default" }, { name: "prompt", type: "text", label: "Prompt", placeholder: "" }] },
  { id: "kk.slime", name: "slime", moduleId: "kimikukiu-llm", status: "RUNNING", category: "llm", description: "slime is an LLM post-training framework for RL Scaling.", params: [{ name: "tensor_model_paralle", type: "number", label: "Tensor Model Paralle", placeholder: "" }, { name: "sglang_mem_fraction_", type: "number", label: "Sglang Mem Fraction ", placeholder: "" }, { name: "slime_specific_argum", type: "text", label: "Slime Specific Argum", placeholder: "" }] },
  { id: "kk.gpt_sovits", name: "GPT-SoVITS", moduleId: "kimikukiu-voice", status: "RUNNING", category: "voice", description: "A powerful few-shot voice conversion and text-to-speech (TTS) web UI that can clone a voice from a small audio sample.", params: [{ name: "vocal_path", type: "text", label: "Vocal Path", placeholder: "" }, { name: "speaker_name", type: "text", label: "Speaker Name", placeholder: "" }, { name: "language", type: "select", label: "Language", options: ["default", "custom"], defaultValue: "default" }] },
  { id: "kk.fuckjews", name: "FuckJews", moduleId: "kimikukiu-exploit", status: "RUNNING", category: "exploitation", description: "A tool for coordinating malicious activities, such as harassment or denial-of-service attacks, against Jewish individual", params: [{ name: "target_url", type: "text", label: "Target Url", placeholder: "" }, { name: "attack_type", type: "select", label: "Attack Type", options: ["default", "custom"], defaultValue: "default" }, { name: "message_template", type: "text", label: "Message Template", placeholder: "" }] },
  { id: "kk.piupiuboomboom", name: "PiuPiuBoomBoom", moduleId: "kimikukiu-security", status: "RUNNING", category: "security", description: "A collection of offensive security tools and scripts for penetration testing, malware development, and AI-powered hackin", params: [{ name: "target_host", type: "text", label: "Target Host", placeholder: "" }, { name: "payload_type", type: "select", label: "Payload Type", options: ["default", "custom"], defaultValue: "default" }, { name: "network_interface", type: "text", label: "Network Interface", placeholder: "" }] },
  { id: "kk.t_bot_otp", name: "T-Bot-otp", moduleId: "kimikukiu-automation", status: "RUNNING", category: "automation", description: "A Telegram bot for managing one-time passwords (OTP).", params: [{ name: "telegram_bot_token", type: "text", label: "Telegram Bot Token", placeholder: "" }, { name: "otp_length", type: "number", label: "Otp Length", placeholder: "" }, { name: "otp_expiration_time", type: "number", label: "Otp Expiration Time", placeholder: "" }] },
];

// ============================================================
// HELPER FUNCTIONS
// ============================================================
export function getToolsByModule(moduleId: string): Tool[] {
  return ALL_TOOLS.filter((t) => t.moduleId === moduleId);
}

export function getToolById(toolId: string): Tool | undefined {
  return ALL_TOOLS.find((t) => t.id === toolId);
}

export function getRunningTools(): Tool[] {
  return ALL_TOOLS.filter((t) => t.status === "RUNNING");
}

export function searchTools(query: string): Tool[] {
  const lq = query.toLowerCase();
  return ALL_TOOLS.filter(
    (t) =>
      t.name.toLowerCase().includes(lq) ||
      t.description.toLowerCase().includes(lq) ||
      t.id.toLowerCase().includes(lq) ||
      t.category.toLowerCase().includes(lq)
  );
}

export function getToolCategories(): string[] {
  return [...new Set(ALL_TOOLS.map((t) => t.category))];
}
